### ISSUE TITLE
Move Objectos HTML to the objectos.way package

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#600]
## Tasks

- [x] html: html.AttributeName will be way.Html.AttributeName
- [x] html: html.TemplateElements will be way.Html.TemplateElements
- [x] html: html.StandardElement will be way.HtmlElementNameGenerated
- [x] html.BaseElements will be way.HtmlCompilerElements
- [x] html: create Script.getBytes() or similar
- [x] html: create Icons or similar
