### ISSUE TITLE
Support parameters in HTTP routes

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#603]
## Tasks

- [x] HtmlModuleCompilerTest: exact01 /foo
- [x] HtmlModuleCompilerTest: exact02 /foo/bar
- [x] HtmlModuleCompilerTest: exact03 /
- [x] HtmlModuleCompilerTest: exact04 'foo' <- error
- [x] HtmlModuleCompilerTest: wildcard01 '/*'
- [x] HtmlModuleCompilerTest: wildcard02 '/foo*'
- [x] HtmlModuleCompilerTest: wildcard03 '/foo/*'
- [x] HtmlModuleCompilerTest: wildcard04 '/foo/*/' <- error
- [x] HtmlModuleCompilerTest: named01 '/foo/:a'
- [x] HtmlModuleCompilerTest: named02 '/foo/:xyz'
- [x] HtmlModuleCompilerTest: named03 '/foo/:foo/bar/:bar'
- [x] HtmlModuleCompilerTest: named04 '/foo/:foo/bar'
- [x] HtmlModuleMatcherTest: exact
- [x] HtmlModuleMatcherTest: wildcard
- [x] HtmlModuleMatcherTest: variable
