### ISSUE TITLE
http: simplify Http.Request hierarchy

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#607]
## Tasks

- [x] remove Segment from Target.Path
- [x] merge Target.Path into Target
- [x] merge Target.Query into Target
- [x] Target.rawQuery must return null if query component is not available
- [x] the Target::queryParamNames method
- [ ] Exchange must not extend Request
- [x] seal the Exchange interface
