### ISSUE TITLE
Move Objectos CSS to the objectos.way package

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#616]
## Tasks

- [x] remove Preflight
- [x] remove CssTemplate hierarchy
- [x] The Objectos CSS main class
- [x] Use Css.entry instead of Map.entry
- [x] Use plain String instead of map entries
- [x] Css.overrideFontSize use "fontSize/lineHeight?/letterSpacing?/fontWeight?" format
- [x] refactor CssGenerator: static table props
- [x]  refactor CssGenerator: prefix table props
- [x] remove CssUtility
- [x] merge CssRule.Of into CssRule
