### ISSUE TITLE
The Carbon DataTable component

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#665]
## Tasks

- [x] The CSS border-style utility
- [x] The CSS::extendColors config
- [x] The CSS::extendSpacing config
- [x] #670

**Comment by marcioendo** [comment]
Carbon was removed from Way (for now at least).
