### ISSUE TITLE
Revamp the Sql.Transaction API

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#692]
## Tasks

- [x] Sql.Transaction#rollbackUnchecked(Throwable original)
- [x] Sql.Transaction#add(Object, int type)
- [x] Sql.Transaction should not be AutoCloseable
- [x] Sql.Transaction#format(Object...)
- [x]  Sql.Transaction#rollbackAndWrap(Throwable original)
- [x]  Sql.Transaction#rollbackAndSuppress(Throwable original)
- [x] Sql.RowMapper#mapRow(ResultSet rs, int parameterHelper)
- [x] Sql.Transaction#querySingle
- [x] Sql.Transaction#queryNullable
- [x] Sql.Transaction#queryOptionalInt
- [x] Sql.IntGeneratedKeys
