### ISSUE TITLE
http: revamp Http

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#699]
## Tasks

- [x] move factory from Http to Http.TestingExchange
- [x] TestingExchange: allow setting the method
- [x] TestingExchange: path parameters
- [x] Exchange: queryParamNames
- [x] Module: route + interceptor
- [x] TestingExchange: allow for response assertion
