### ISSUE TITLE
html: introduce the 'testField' instruction

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#701]
## Tasks

- [x] remove Html.nextId
- [x] remove AttributeName.EXECUTE_DEFAULT
- [x] Html.Compiler should not be public

## Allow

Write in a template:

```java
class MyTemplate extends Html.Template {
  @Override
  protected final void render() {
    div(
      div(testField("x"), t("123")),
      div(testField("y"), t("abc")),
    );
  }
}
```

It should be rendered as:

```html
<div>
<div>123</div>
<div>abc</div>
</div>
```

And Html.Compiler::toTestString() should render:

```
x: 123
y: abc
```
