### ISSUE TITLE
html: revamp Html

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#702]
## Tasks

- [x] Html.Compiler::compile should not be public
- [x] Simplify pseudo-dom hierarchy
- [x] Simplify instruction hierarchy
- [x] EXECUTE_DEFAULT
- [x] testable should be an element: testable("foo-bar", value)
- [x] use proper method name for text
- [x] use proper method name for includes
- [x] allow including plugins
